services:
  tracker:
    build: .
    restart: unless-stopped
    mem_limit: 3g
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    networks:
      - bittorrent-tracker-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - redis-data:/data
    networks:
      - bittorrent-tracker-network

volumes:
  redis-data:

networks:
  bittorrent-tracker-network:
